from enum import Enum

class CaseState(str, Enum):
    REFUND_FAILED = "REFUND_FAILED"
    CLASSIFIED = "CLASSIFIED"
    AWAITING_ALTERNATE = "AWAITING_ALTERNATE"
    ALTERNATE_SUBMITTED = "ALTERNATE_SUBMITTED"
    INVESTIGATING = "INVESTIGATING"
    RISK_SCORED = "RISK_SCORED"
    APPROVED = "APPROVED"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    NEEDS_INFORMATION = "NEEDS_INFORMATION"
    PAYOUT_PENDING = "PAYOUT_PENDING"
    PAYOUT_SUCCESS = "PAYOUT_SUCCESS"
    PAYOUT_FAILED = "PAYOUT_FAILED"
    DUPLICATE_GUARD_TRIGGERED = "DUPLICATE_GUARD_TRIGGERED"
    RESOLVED = "RESOLVED"
    CASE_EXPIRED = "CASE_EXPIRED"

ALLOWED_TRANSITIONS = {
    CaseState.REFUND_FAILED: {CaseState.CLASSIFIED, CaseState.CASE_EXPIRED},
    CaseState.CLASSIFIED: {CaseState.AWAITING_ALTERNATE, CaseState.CASE_EXPIRED},
    CaseState.AWAITING_ALTERNATE: {CaseState.ALTERNATE_SUBMITTED, CaseState.CASE_EXPIRED},
    CaseState.ALTERNATE_SUBMITTED: {CaseState.INVESTIGATING, CaseState.CASE_EXPIRED},
    CaseState.INVESTIGATING: {CaseState.RISK_SCORED, CaseState.CASE_EXPIRED},
    CaseState.RISK_SCORED: {CaseState.APPROVED, CaseState.REVIEW, CaseState.REJECTED, CaseState.CASE_EXPIRED},
    CaseState.REVIEW: {CaseState.APPROVED, CaseState.REJECTED, CaseState.NEEDS_INFORMATION, CaseState.CASE_EXPIRED},
    CaseState.NEEDS_INFORMATION: {CaseState.AWAITING_ALTERNATE, CaseState.CASE_EXPIRED},
    CaseState.APPROVED: {CaseState.DUPLICATE_GUARD_TRIGGERED, CaseState.PAYOUT_PENDING, CaseState.CASE_EXPIRED},
    CaseState.DUPLICATE_GUARD_TRIGGERED: {CaseState.RESOLVED, CaseState.CASE_EXPIRED},
    CaseState.REJECTED: set(),
    CaseState.PAYOUT_PENDING: {CaseState.PAYOUT_SUCCESS, CaseState.PAYOUT_FAILED},
    CaseState.PAYOUT_SUCCESS: {CaseState.RESOLVED},
    CaseState.PAYOUT_FAILED: {CaseState.RISK_SCORED, CaseState.RESOLVED},
    CaseState.RESOLVED: set(),
    CaseState.CASE_EXPIRED: set(),
}
